-- 1.
SELECT DEPARTMENT_NAME AS "학과명" , CATEGORY AS "계열"
FROM TB_DEPARTMENT;

-- 2.
SELECT DEPARTMENT_NAME ||'의 정원은' AS "학과별", CAPACITY||' 명 입니다.' AS "정원"
FROM TB_DEPARTMENT;

-- 3.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO='001' AND ABSENCE_YN = 'Y' 
AND SUBSTR(STUDENT_SSN,8,1) IN ('2','4');

-- 4.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE STUDENT_NO IN ('A513079', 'A513090','A513091', 'A513110','A513119')
ORDER BY STUDENT_NAME DESC;

-- 5.
SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT
WHERE CAPACITY BETWEEN 20 AND 30;

-- 6.
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO IS NULL;

-- 7.
SELECT STUDENT_NAME
FROM TB_STUDENT
WHERE DEPARTMENT_NO IS NULL;

-- 8.
SELECT CLASS_NO
FROM TB_CLASS
WHERE PREATTENDING_CLASS_NO IS NOT NULL;

-- 9.
SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT;

-- 10.
SELECT STUDENT_NO, STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'N' AND SUBSTR(STUDENT_NO, 1,2) = 'A2'
AND SUBSTR(STUDENT_ADDRESS,1,2) = '전주';

-- Additional SELECT 
-- 1.
SELECT STUDENT_NO, STUDENT_NAME ,ENTRANCE_DATE
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY ENTRANCE_DATE;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___%' OR PROFESSOR_NAME LIKE '%____';

-- 3.
SELECT PROFESSOR_NAME AS "교수이름", EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM(TO_DATE(SUBSTR(PROFESSOR_SSN,1,6),'RRMMDD')))
FROM TB_PROFESSOR;
--ORDER BY "나이";

SELECT EXTRACT(YEAR FROM SYSDATE)
FROM TB_PROFESSOR;

-- 4.

