-- KH_연습문제 JOIN
-- 1.
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_CODE
FROM EMPLOYEE,DEPARTMENT
WHERE DEPT_CODE = DEPT_ID
AND SUBSTR(EMP_NO,1,2) IN ('70','71','72','73','74','75','76','77','78','79')
AND EMP_NAME LIKE '전%';

-- 2.
SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD'))) AS "나이", DEPT_TITLE, JOB_CODE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD')))
FROM EMPLOYEE;

SELECT EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6 ))))
FROM EMPLOYEE;

SELECT TO_DATE(SUBSTR(EMP_NO,1,6))
FROM EMPLOYEE;

-- 3.
SELECT EMP_NAME, JOB_NAME, DEPT_CODE, DEPT_TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT * FROM EMPLOYEE;
SELECT * FROM DEPARTMENT;