-- KH_연습문제 JOIN
-- 1.
SELECT EMP_NAME, EMP_NO, DEPT_TITLE, JOB_CODE
FROM EMPLOYEE,DEPARTMENT
WHERE DEPT_CODE = DEPT_ID
AND SUBSTR(EMP_NO,1,2) IN ('70','71','72','73','74','75','76','77','78','79')
AND EMP_NAME LIKE '전%';

-- 2.
SELECT EMP_ID, EMP_NAME, EXTRACT(YEAR FROM SYSDATE)-EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD'))) AS "나이", DEPT_TITLE, JOB_CODE
FROM EMPLOYEE, DEPARTMENT
WHERE DEPT_CODE = DEPT_ID;

SELECT EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6),'RRMMDD')))
FROM EMPLOYEE;

SELECT EXTRACT(YEAR FROM(TO_DATE(SUBSTR(EMP_NO,1,6 ))))
FROM EMPLOYEE;

SELECT TO_DATE(SUBSTR(EMP_NO,1,6))
FROM EMPLOYEE;

-- 3.
SELECT EMP_ID, EMP_NAME, JOB_NAME
FROM EMPLOYEE E, JOB J
WHERE E.JOB_CODE = J.JOB_CODE
AND EMP_NAME LIKE '%형%';

--4.
SELECT *
FROM(SELECT E.EMP_NAME,J.JOB_NAME,E.DEPT_CODE, D.DEPT_TITLE
FROM EMPLOYEE E, DEPARTMENT D, JOB J
WHERE DEPT_CODE = DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND E.DEPT_CODE IN ('D5' , 'D6')
ORDER BY DEPT_CODE DESC, EMP_NAME);

--5.
SELECT *
FROM(SELECT E.EMP_NAME, E.BONUS, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE)
WHERE BONUS IS NOT NULL;


--6.
SELECT E.EMP_NAME, J.JOB_NAME, D.DEPT_TITLE, L.LOCAL_NAME
FROM EMPLOYEE E, JOB J, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND E.JOB_CODE = J.JOB_CODE
AND D.LOCATION_ID = L.LOCAL_CODE;

--7.
SELECT E.EMP_NAME, D.DEPT_TITLE, L.LOCAL_NAME, NATIONAL_CODE
FROM EMPLOYEE E, DEPARTMENT D, LOCATION L
WHERE E.DEPT_CODE = D.DEPT_ID
AND D.LOCATION_ID = L.LOCAL_CODE
AND NATIONAL_CODE IN ('KO', 'JP')
ORDER BY EMP_ID;

--8.
SELECT D.EMP_NAME, E.DEPT_CODE, E.EMP_NAME
FROM EMPLOYEE E, EMPLOYEE D
WHERE E.DEPT_CODE = D.DEPT_CODE
AND D.EMP_NAME != E.EMP_NAME
ORDER BY D.EMP_NAME;

--9.
SELECT EMP_NAME, JOB_NAME, SALARY+SALARY*(NVL(BONUS,0))
FROM EMPLOYEE
JOIN JOB USING (JOB_CODE)
WHERE BONUS IS NULL
AND JOB_CODE IN ('J4', 'J7');

--10.
SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, ROWNUM
FROM (SELECT EMP_ID, EMP_NAME, DEPT_TITLE, JOB_NAME, HIRE_DATE, (SALARY + SALARY * NVL(BONUS,0))*12 AS "연봉"
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_CODE = DEPT_ID
JOIN JOB USING(JOB_CODE)
ORDER BY 연봉 DESC)
WHERE ROWNUM <= 5;

--11_1
SELECT DEPT_TITLE, SUM(SALARY)
FROM EMPLOYEE
JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) >= 64886240 *0.2;

--11_2
SELECT DEPT_TITLE, SUM(SALARY)
FROM (SELECT DEPT_TITLE, SALARY
    FROM EMPLOYEE
    JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE)
GROUP BY DEPT_TITLE
HAVING SUM(SALARY) >= 64886240 *0.2 ;

--12
SELECT DEPT_TITLE, SUM(SALARY)
FROM (SELECT DEPT_TITLE , SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON DEPT_ID = DEPT_CODE)
GROUP BY DEPT_TITLE;
