-- 테이블 생성
/*
1. 컬럼 최소 7개
2. PRIMARY KEY 1개 이상
3. NOT NULL
4. UNIQUE, CHECK (택1)
5. 제약조건명 필수!!!

인서트문 적어도 5개씩

자료형 : VARCHAR2, CHAR, NUMBER, DATE
=> 3개이상 들어가게 테이블 만들어볼 것!!!
*/
DROP TABLE MCD_MENU;

CREATE TABLE MCD_MENU(
    WAITING_NAME VARCHAR2(20),
    MENU_NO NUMBER,
    MENU_NAME VARCHAR2(20) NOT NULL,
    PRICE NUMBER NOT NULL,
    RESTAURANT_CODE NUMBER NOT NULL,
    FOOD CHAR(3) CHECK(FOOD IN ('Y','N')),
    STARSCORE NUMBER,
    PRIMARY KEY (WAITING_NAME, MENU_NO)
);

COMMENT ON COLUMN MCD_MENU.WAITING_NAME IS '대기자';
COMMENT ON COLUMN MCD_MENU.MENU_NO IS '메뉴번호';
COMMENT ON COLUMN MCD_MENU.MENU_NAME IS '메뉴이름';
COMMENT ON COLUMN MCD_MENU.PRICE IS '가격';
COMMENT ON COLUMN MCD_MENU.RESTAURANT_CODE IS '매장코드';
COMMENT ON COLUMN MCD_MENU.FOOD IS '음식여부';
COMMENT ON COLUMN MCD_MENU.STARSCORE IS '음식평점';

INSERT INTO MCD_MENU
VALUES('한수빈', '1', '빅맥', 8200, '0624', 'Y', '4.5');
INSERT INTO MCD_MENU
VALUES('최영재', '1', '빅맥', 8200, '0624', 'Y', '3.5');
INSERT INTO MCD_MENU
VALUES('김수진', '2', '불고기', 5800, '0624', NULL, NULL);

SELECT * FROM MCD_MENU;

CREATE TABLE SURVEY(
    SURVEY_CODE NUMBER,
    RESTAURANT_CODE NUMBER,
    SERVICE_LEVEL NUMBER NOT NULL,
    CLEAN_SCORE NUMBER,
    IMPROVEMENT_POINTS VARCHAR2(50),
    SURVEY_WRITER VARCHAR2(20),
     PRIMARY KEY (SURVEY_CODE, RESTAURANT_CODE)
);

COMMENT ON COLUMN SURVEY.SURVEY_CODE IS '작성자번호';
COMMENT ON COLUMN SURVEY.RESTAURANT_CODE IS '매장코드';
COMMENT ON COLUMN SURVEY.SERVICE_LEVEL IS '서비스만족도';
COMMENT ON COLUMN SURVEY.CLEAN_SCORE IS '청결도';
COMMENT ON COLUMN SURVEY.IMPROVEMENT_POINTS IS '개선점';
COMMENT ON COLUMN SURVEY.SURVEY_WRITER IS '작성자';

INSERT INTO SURVEY
VALUES( 1, 0624, 3.9, 3.5, '매장이 더러워요' , NULL);
INSERT INTO SURVEY
VALUES( 2, 0624, 4.0, 3.9, '소스가 너무적어요' , '비밀');

SELECT * FROM SURVEY;

DROP TABLE RESTAURANT;
CREATE TABLE RESTAURANT(
    RESTAURANT_NAME VARCHAR2(50) NOT NULL UNIQUE,
    RESTAURANT_CODE VARCHAR2(20) NOT NULL UNIQUE
);

COMMENT ON COLUMN RESTAURANT.RESTAURANT_NAME IS '매장이름';
COMMENT ON COLUMN RESTAURANT.RESTAURANT_CODE IS '매장번호';

INSERT INTO RESTAURANT
VALUES ( '제주서귀포월드컵점DT점' , '0624');
INSERT INTO RESTAURANT
VALUES ( '서귀포 DT점' , '0523');
INSERT INTO RESTAURANT
VALUES ( ' 제주중문 DT점', '0726');

SELECT * FROM RESTAURANT;



