-- 1
CREATE USER ID IDENTIFIED BY PW;
GRANT CONNECT, RESOURCE TO ID;


-- 2
SELECT DEPT_CODE, JOB_CODE, SALARY
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE, SALARY;
-- JOB_CODE가 그룹으로 묶여있지않고, SALARY는 그룹함수(SUM)를 사용하거나 그룹BY로 묶여야한다.


SELECT DEPT_CODE, JOB_CODE, SUM(SALARY)
FROM EMPLOYEE
GROUP BY DEPT_CODE, JOB_CODE;
-- SELECT 절에 그룹BY로 묶여있고, 그룹함수를 사용하여야한다.